// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEk31Z0lVrJmBN7nBjYUTXBd4fWSlm1eE',
    appId: '1:991585268640:web:146c52409b0b898aeeeac5',
    messagingSenderId: '991585268640',
    projectId: 'acarris-f083e',
    authDomain: 'acarris-f083e.firebaseapp.com',
    storageBucket: 'acarris-f083e.appspot.com',
    measurementId: 'G-T9MZWZJ81B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCG3DvcreOixkMG-9cIyQ9NkYxbwN_8qoA',
    appId: '1:991585268640:android:f27b315870e3b983eeeac5',
    messagingSenderId: '991585268640',
    projectId: 'acarris-f083e',
    storageBucket: 'acarris-f083e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJgRcnddUB8ssuyXHkgUYvznWutqgKQjM',
    appId: '1:991585268640:ios:628be2df59b3ee7deeeac5',
    messagingSenderId: '991585268640',
    projectId: 'acarris-f083e',
    storageBucket: 'acarris-f083e.appspot.com',
    iosBundleId: 'com.example.acarreos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJgRcnddUB8ssuyXHkgUYvznWutqgKQjM',
    appId: '1:991585268640:ios:0a69b5f884c9cc04eeeac5',
    messagingSenderId: '991585268640',
    projectId: 'acarris-f083e',
    storageBucket: 'acarris-f083e.appspot.com',
    iosBundleId: 'com.example.acarreos.RunnerTests',
  );
}
